import { useState } from 'react'

const words = ['perro', 'gato', 'avión'] as const

export function EmbeddingsScene() {
  const [selected, setSelected] = useState<typeof words[number]>('perro')
  return (
    <section className="learning-scene" id="embeddings" aria-labelledby="embeddings-title">
      <header className="scene-heading"><p className="eyebrow">05 / RELACIONES EN EL ESPACIO</p><h2 id="embeddings-title">Un mapa de <em>significados.</em></h2><p>Podemos aprender a colocar palabras de modo que su cercanía refleje algo de lo que tienen en común.</p></header>
      <div className="meaning-layout">
        <div className="meaning-copy"><h3>La posición también cuenta.</h3><p>Perro y gato pueden quedar próximos por sus usos relacionados. Avión puede quedar más lejos. Ahora la geometría expresa una relación que las casillas de one-hot no mostraban.</p><p>El nombre técnico es <strong>embedding</strong>: una lista de números —un vector— cuya posición y dirección en un espacio contienen información útil sobre relaciones.</p><div className="word-selector" role="group" aria-label="Explorar una palabra en el mapa">{words.map(word => <button key={word} aria-pressed={selected === word} onClick={() => setSelected(word)}>{word}</button>)}</div><p className="visual-explanation" aria-live="polite">{selected === 'avión' ? 'Avión queda separado de los dos animales en este dibujo. No estamos midiendo una distancia real.' : `${selected === 'perro' ? 'Perro tiene a gato' : 'Gato tiene a perro'} cerca: la proximidad ilustra una relación de significado, no que sean lo mismo.`}</p></div>
        <figure className="embedding-map"><svg viewBox="0 0 600 380" role="img" aria-labelledby="map-title map-description"><title id="map-title">Mapa conceptual de perro, gato y avión</title><desc id="map-description">Perro y gato próximos a la izquierda; avión alejado a la derecha. Las posiciones son ilustrativas.</desc><path className="map-grid" d="M40 80H560M40 160H560M40 240H560M40 320H560M100 40V340M200 40V340M300 40V340M400 40V340M500 40V340"/><path className="map-relation" d={selected === 'avión' ? 'M180 240L465 105L255 205' : 'M180 240L255 205'}/>{[{ word: 'perro', x: 180, y: 240 }, { word: 'gato', x: 255, y: 205 }, { word: 'avión', x: 465, y: 105 }].map(point => <g key={point.word} className={selected === point.word ? 'map-point selected' : 'map-point'}><circle cx={point.x} cy={point.y} r={selected === point.word ? 13 : 7}/><text x={point.x} y={point.y - 25} textAnchor="middle">{point.word}</text></g>)}</svg><figcaption className="experiment-note">Ilustración conceptual, no salida real ni espacio completo. Un embedding real suele tener muchas dimensiones; este mapa 2D solo ayuda a imaginarlo. Sus ejes no son necesariamente conceptos con nombre.</figcaption></figure>
      </div>
      <div className="lesson-block"><p className="eyebrow">CÓMO SE APRENDE LA RELACIÓN</p><h3>Las palabras dejan pistas a su alrededor.</h3><p>Si perro y gato aparecen en contextos parecidos, esas pistas pueden acercar sus representaciones. <strong>Word2Vec</strong> fue un hito histórico para aprender relaciones así: <span className="numeric">Word to Vector</span>, palabra → vector.</p><div className="paired-explanations"><div><h4>CBOW</h4><p>Contexto → palabra</p><p className="experiment-note">«El ___ duerme» → intentar predecir «gato».</p></div><div><h4>Skip-gram</h4><p>Palabra → contexto</p><p className="experiment-note">«gato» → intentar predecir palabras que aparecen alrededor, como «duerme».</p></div></div><p className="experiment-note">Esquemas de aprendizaje, no predicciones calculadas aquí. Word2Vec ayuda a entender la idea; no es el método del modelo que usaremos en la práctica.</p></div>
      <div className="scene-takeaway"><span aria-hidden="true">↔</span><p><strong>Aprender del contexto no significa cambiar con cada frase.</strong> Word2Vec produce, conceptualmente, un embedding estático por palabra: una vez aprendido, usa la misma representación aunque cambie la frase.</p></div>
      <a className="scene-bridge" href="#contexto">¿Y si una misma palabra tiene dos sentidos? <span aria-hidden="true">↓</span></a>
    </section>
  )
}
